### ISSUE TITLE
error message "webdav: prefix mismatch"

### ISSUE THREAD

**Issue by clan4456** [pluveto/flydav#11]
Hello, developer!
I tested Flydav on Windows11 and found the following problems:

Run "flydav" in the command line to access Webdav successful. The actual physical path is C:\Users\xxx\AppData\Local\Temp\flydav. 

Run "flydav.exe -c flydav.toml", The log sends an error message indicating "webdav: prefix mismatch". And cannot access Webdav.

May I ask if my configuration file was incorrectly configured? Thanks!
[flydav.toml.txt](https://github.com/pluveto/flydav/files/11175712/flydav.toml.txt)
[webdav.log](https://github.com/pluveto/flydav/files/11175713/webdav.log)

**Comment by pluveto** [comment]
`sub_fs_dir` should be a relative path, please check

**Comment by clan4456** [comment]
I tested the following, all with the same error

sub_fs_dir = ""
sub_fs_dir = "/"
sub_fs_dir = "\\\\"

**Comment by pluveto** [comment]
Do you have any folder called /clan/?

**Comment by clan4456** [comment]
fs_dir = "D:\\tmp"
    [[auth.user]]
    username = "clan"
    sub_fs_dir = ""
    sub_path = ""

Now I changed the above configurations, WebDAV work successful.

but I don't understand the mapping relationship between sub_fs_dir sub_path and actual physical path

**Comment by pluveto** [comment]
`fs` means file-system
`path` or `sub_path` is only a part of url

These naming may be confusing, I'll appreciate it if you can help me assign them better names.

**Comment by clan4456** [comment]
I can understand the name of fs, path , sub_path. I just don't understand the mapping relationship between sub_fs_dir and actual physical path.

For example, I configured the following parameters:

host = "127.0.0.1"
port = 7086
path = "/webdav"
fs_dir = "D:\\tmp"

    [[auth.user]]
    username = "clan"
    sub_fs_dir = "clan"
    sub_path = "/clan"

Which physical path does the webdav url "127.0.0.1:7086/webdav" and "127.0.0.1:7086/webdav/clan"  actually point to?

**Comment by pluveto** [comment]
`127.0.0.1:7086/webdav/clan` will be mapped to `D:/tmp/clan`
`127.0.0.1:7086/webdav` will be mapped to `127.0.0.1:7086/webdav`
Usename has nothing to do with file system dir.

**Comment by clan4456** [comment]
OK, I see.

thanks for your answer!
