### ISSUE TITLE
How to reset my password?

### ISSUE THREAD

**Issue by RookieTerry** [pluveto/flydav#16]
I had forgotten my password,and I tried to cover the former password by starting with configuration file, but failed. How to reset my password of the user flydav? And when can you support HTTPS?

**Comment by RookieTerry** [comment]
I ran you program on a Windows PC, so how to start up the program when booting?

**Comment by pluveto** [comment]
You can reset password by generating a bcrypt encoded string with any bcrypt online tool. HTTPS will be native supported in next version and now you can use nginx as a reverse proxy to support TLS
