### ISSUE TITLE
Automatically create directory sub_fs_dir

### ISSUE THREAD

**Issue by shilazi** [pluveto/flydav#18]
When `sub_fs_dir` is added for `user`

```yaml
auth:
  user:
  - username: flydav
    password_hash: 'password_hash'
    password_crypt: bcrypt
    sub_path: /sub
    sub_fs_dir: sub
```

An error will be reported if the `sub_fs_dir` is not created manually

```
DEBU[0000] FsDir: /tmp/flydav
INFO[0005] request: PROPFIND/webdav/sub/
INFO[0005] request: PROPFIND/webdav/sub/
ERRO[0006] stat /tmp/flydav/sub: no such file or directory  method=PROPFIND path=/webdav/sub/
```

Can you add the ability to create `sub_fs_dir` automatically? Thanks.

https://github.com/pluveto/flydav/blob/d2e49503dded5f31cf1992acaed3c12ba0f4f084/cmd/flydav/app/webdav.go#L129-L134

**Comment by pluveto** [comment]
This feature is now supported
