### ISSUE TITLE
readme 中的 FlyDav UI 无效

### ISSUE THREAD

**Issue by hhs66317** [pluveto/flydav#5]
我参考 readme 及配置文件模板修改的
```
[ui]
enabled = true
path = "/ui"
source = "/usr/share/flydav/ui"
```
但并不能像 readme 中一样，在浏览器中访问

**Comment by pluveto** [comment]
UI need to be installed seperately. A tutorial will come in 30 minutes.

**Comment by pluveto** [comment]
Try the ui_installer script

**Comment by hhs66317** [comment]
我没有找到你说的UI使用教程
我看了 ui_installer 脚本文件，我是手动操作的，分别下载了 可执行程序 flydav 和 ui 压缩包，将ui压缩包解压到 /usr/share/flydav/ui ，在配置文件中配置之后，然后用配置启动了 flydav ，依然无法通过浏览器访问  http://127.0.0.1:7086/ui


完整配置文件如下：
```
[server]
host = "0.0.0.0"
port = 7086
path = ""
fs_dir = "/opt"

[ui]
enabled = true
path = "/ui"
source = "/opt/usr/share/flydav/ui"

[auth]
    [[auth.user]]
    username = "matthew"
    sub_fs_dir = "/etc/"
    sub_path = ""
    password_hash = "99c3b031ec66335ae36b6687d5ec778a11915bb232c905079abbb6b8cdd927b5"
    password_crypt = "sha256"
    [[auth.user]]
    username = "admin"
    sub_fs_dir = "/usr/"
    sub_path = ""
    password_hash = "99c3b031ec66335ae36b6687d5ec778a11915bb232c905079abbb6b8cdd927b5"
    password_crypt = "sha256"
    # add more users here
    # note: the above line is required by auto install script, do not delete.

[log]
# level = "Debug"
level = "Trace"
    [[log.file]]
    format = "json"
    path = "/var/log/flydav.log"
    max_size = 1 # megabytes
    max_age = 28 # days

    [[log.stdout]]
    format = "text" # or "text"
    output = "stdout" # or "stderr"

[cors]
enabled = true
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "PROPFIND", "PROPPATCH", "MKCOL", "COPY", "MOVE", "LOCK", "UNLOCK", "OPTIONS", "HEAD", "PATCH"]
allowed_headers = ["*"]
exposed_headers = ["*"]
allow_credentials = true
max_age = 86400 # seconds

```

**Comment by hhs66317** [comment]
> 我没有找到你说的UI使用教程 我看了 ui_installer 脚本文件，我是手动操作的，分别下载了 可执行程序 flydav 和 ui 压缩包，将ui压缩包解压到 /usr/share/flydav/ui ，在配置文件中配置之后，然后用配置启动了 flydav ，依然无法通过浏览器访问 http://127.0.0.1:7086/ui
> 
> 完整配置文件如下：
> 
> ```
> [server]
> host = "0.0.0.0"
> port = 7086
> path = ""
> fs_dir = "/opt"
> 
> [ui]
> enabled = true
> path = "/ui"
> source = "/opt/usr/share/flydav/ui"
> 
> [auth]
>     [[auth.user]]
>     username = "matthew"
>     sub_fs_dir = "/etc/"
>     sub_path = ""
>     password_hash = "99c3b031ec66335ae36b6687d5ec778a11915bb232c905079abbb6b8cdd927b5"
>     password_crypt = "sha256"
>     [[auth.user]]
>     username = "admin"
>     sub_fs_dir = "/usr/"
>     sub_path = ""
>     password_hash = "99c3b031ec66335ae36b6687d5ec778a11915bb232c905079abbb6b8cdd927b5"
>     password_crypt = "sha256"
>     # add more users here
>     # note: the above line is required by auto install script, do not delete.
> 
> [log]
> # level = "Debug"
> level = "Trace"
>     [[log.file]]
>     format = "json"
>     path = "/var/log/flydav.log"
>     max_size = 1 # megabytes
>     max_age = 28 # days
> 
>     [[log.stdout]]
>     format = "text" # or "text"
>     output = "stdout" # or "stderr"
> 
> [cors]
> enabled = true
> allowed_origins = ["*"]
> allowed_methods = ["GET", "POST", "PUT", "DELETE", "PROPFIND", "PROPPATCH", "MKCOL", "COPY", "MOVE", "LOCK", "UNLOCK", "OPTIONS", "HEAD", "PATCH"]
> allowed_headers = ["*"]
> exposed_headers = ["*"]
> allow_credentials = true
> max_age = 86400 # seconds
> ```

忘了 @pluveto 你了

**Comment by hhs66317** [comment]
@pluveto 
我用你最新编译的 v0.2.46，按之前的方法尝试了下，现在可以用 http://127.0.0.1:7086/ui 打开了，但是没有文件列表，在 http://127.0.0.1:7086/ui 中也正确设置了服务器信息，直接访问 http://127.0.0.1:7086/webdav，显示 Not Found

**Comment by hhs66317** [comment]
> @pluveto 我用你最新编译的 v0.2.46，按之前的方法尝试了下，现在可以用 http://127.0.0.1:7086/ui 打开了，但是没有文件列表，在 http://127.0.0.1:7086/ui 中也正确设置了服务器信息，直接访问 [http://127.0.0.1:7086/webdav，显示](http://127.0.0.1:7086/webdav%EF%BC%8C%E6%98%BE%E7%A4%BA) Not Found

我错了，我修改了配置文件中的 server.path 为 ”“，通过日志发现问题后，修改了 http://127.0.0.1:7086/ui 的配置信息后，现在可以在 http://127.0.0.1:7086/ui 中浏览 webdav 的内容了

**Comment by pluveto** [comment]
好的，目前 UI 还在开发中，欢迎帮忙
