### ISSUE TITLE
amd64 version can not read config file 

### ISSUE THREAD

**Issue by maxkimkim** [pluveto/flydav#9]
Hello! I downloaded the flydav-app-windows-amd64.zip version and used the command line flydav.exe -config D:\FlyDav\flydav.toml to start with the configuration file, but the default configuration is still used. How should I write it?

**Comment by pluveto** [comment]
两个----- On Thu, 2023-02-16 14:57:46  ***@***.***> wrote ----  
你好！我下载了 flydav-app-windows-amd64.zip 版本，使用命令行 flydav.exe -config D:FlyDavlydav.toml 带配置文件启动，但还是用默认配置，请问怎么写才对？

**Comment by hhs66317** [comment]
@maxkimkim Windows

The ”\“ in the path under Windows needs to be escape,So If the configuration cannot be analyzed correctly, the default settings will be used

for example
```
[server]
host = "0.0.0.0"
port = 7086
path = ""
fs_dir = "C:\\berrybrew"
```

But the UI path in the configuration cannot be processed correctly，There is no problem under Linux，This requires @Pluveto to handle

```
[ui]
enabled = true
path = "/ui"
source = "F:\\soft\\flydav\\ui"
```

**Comment by maxkimkim** [comment]
It have been solved.
Thank you very much!

hhs66317 ***@***.***> 于2023年2月16日周四 15:47写道：
